[package]
name = "application"
version = "0.1.0"
edition = "2021"
authors = ["Pietro Bertorelle","Francesco Abate","Elio Magliari"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
druid = "0.8.3"
tracing = "0.1.37"